name: Build NikkeTools

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish C# Projects & Build C++
        run: |
          New-Item -ItemType Directory -Force -Path output_dist

          # 1. C# (.NET) 프로젝트들을 실행에 필요한 의존성 파일과 함께 Publish
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            Write-Host "Publishing C# Project: $($_.FullName)"
            dotnet publish $_.FullName -c Release -o output_dist --no-self-contained
          }

          # 2. C++ (.vcxproj) 프로젝트 빌드 및 output_dist로 복사
          Get-ChildItem -Recurse -Filter *.vcxproj | ForEach-Object {
            Write-Host "Building C++ Project: $($_.FullName)"
            msbuild $_.FullName /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143
          }
          
          # C++ 결과물(.exe, .dll) output_dist 폴더로 수집
          Get-ChildItem -Recurse -Include *.exe, *.dll | Where-Object { 
            $_.FullName -notlike "*\output_dist\*" -and 
            $_.FullName -notlike "*\obj\*" -and 
            $_.FullName -notlike "*\ref\*" 
          } | Copy-Item -Destination output_dist -Force
        shell: powershell

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v4
        with:
          name: NikkeTools-Compiled
          path: output_dist/
