name: Build NikkeTools

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Find and Build Solution
        run: |
          $sln = Get-ChildItem -Recurse -Filter *.sln | Select-Object -First 1
          if (-not $sln) {
            Write-Error "Solution file (.sln) not found!"
            exit 1
          }
          Write-Host "Found solution: $($sln.FullName)"
          
          # Restore & Build
          msbuild $sln.FullName -t:restore
          msbuild $sln.FullName /p:Configuration=Release /p:Platform="x64" /p:PlatformToolset=v143
        shell: powershell

      - name: Collect Output Files
        run: |
          New-Item -ItemType Directory -Force -Path output
          Get-ChildItem -Recurse -Include *.exe, *.dll, *.bat, *.py, *.proto | Where-Object { $_.FullName -notlike "*\obj\*" } | Copy-Item -Destination output -Force
        shell: powershell

      - name: Upload Compiled Files
        uses: actions/upload-artifact@v4
        with:
          name: NikkeTools-Compiled
          path: output/
